// global.css assembly — the CLI channel's artifact.
//
// Panels are the source of truth for what they CAN express (colors, 9 text
// slots); global.css carries what they cannot: the spacing scale, overflow
// type styles, and --vsp-color-* reinforcement variables. Output is fully
// deterministic (no timestamps) so BuildPlans and snapshots stay diffable.

const HEADER = [
	'/*',
	' * global.css — generated by @vespasian/wix-driver. DO NOT HAND-EDIT.',
	' * Wix Studio custom CSS (src/styles/global.css via Git integration).',
	' * Theme panels remain the source of truth for colors/text slots; this file',
	' * carries the spacing scale, overflow type styles, and token variables.',
	' */',
].join('\n');

/**
 * @param {Object} parts
 * @param {{ siteColors: Array<{ slug: string, value: string }>, truncated?: string[] }} [parts.colors]
 * @param {Array<{ slug: string, value: string }>} [parts.allColors]  Full palette incl. truncated (for --vsp-color-*).
 * @param {{ overflow: Array<{ className: string, fontSize: string }> }} [parts.typography]
 * @param {string} [parts.spacingCss]  Pre-rendered block from spacing.js.
 * @returns {string}
 */
export function assembleGlobalCss({ colors, allColors, typography, spacingCss } = {}) {
	const sections = [HEADER];

	const colorVars = allColors ?? colors?.siteColors ?? [];
	if (colorVars.length > 0) {
		const lines = ['/* Design-token color variables (reinforcement; panels set the real theme). */', ':root {'];
		for (const color of colorVars) {
			lines.push(`\t--vsp-color-${color.slug}: ${color.value};`);
		}
		lines.push('}');
		sections.push(lines.join('\n'));
	}

	if (spacingCss) {
		sections.push(['/* Spacing scale — Wix has no spacing tokens; this is their only home. */', spacingCss].join('\n'));
	}

	if (typography?.overflow?.length > 0) {
		const lines = ['/* Type-ramp overflow — steps beyond the 9 Wix text-theme slots. */'];
		for (const style of typography.overflow) {
			lines.push(`.${style.className} { font-size: ${style.fontSize}; }`);
		}
		sections.push(lines.join('\n'));
	}

	return `${sections.join('\n\n')}\n`;
}
